// <auto-generated />
namespace Public_Blog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class posttagremoverequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(posttagremoverequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201512212216275_post-tag-remove-required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
