// <auto-generated />
namespace Public_Blog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Images_and_image_in_post : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Images_and_image_in_post));
        
        string IMigrationMetadata.Id
        {
            get { return "201512140522076_Images_and_image_in_post"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
