// <auto-generated />
namespace Public_Blog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class tag_back1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tag_back1));
        
        string IMigrationMetadata.Id
        {
            get { return "201512122337171_tag_back1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
