// <auto-generated />
namespace Public_Blog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class posts_on_tags1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(posts_on_tags1));
        
        string IMigrationMetadata.Id
        {
            get { return "201512130005303_posts_on_tags1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
