// <auto-generated />
namespace Public_Blog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class name_is_key : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(name_is_key));
        
        string IMigrationMetadata.Id
        {
            get { return "201512122339478_name_is_key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
