// <auto-generated />
namespace Public_Blog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class post_fix_no_nullable_field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(post_fix_no_nullable_field));
        
        string IMigrationMetadata.Id
        {
            get { return "201512192329358_post_fix_no_nullable_field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
